name: Creating mediainfo TAR

on:
  push:
    branches: [master]
    paths-ignore: "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clearing cache
        continue-on-error: true
        run: |
          sudo rm -rf /var/cache/apt/archives/*.deb vendor tempx
          sudo apt-get remove libmms0 mediainfo -y

      - name: Downloading required packages
        continue-on-error: true
        run: |
          wget -qq https://mediaarea.net/repo/deb/repo-mediaarea_1.0-16_all.deb && sudo dpkg -i repo-mediaarea_1.0-16_all.deb
          sudo apt-get update && sudo apt-get install --download-only -y libmms0 mediainfo
          mkdir -p tempx vendor
          sudo mv /var/cache/apt/archives/*deb tempx

      - name: Unpacking Debs
        continue-on-error: true
        run: |
          for DEB in $(ls -1 tempx/*.deb); do
            sudo dpkg -x $DEB vendor
          done
          sudo mv vendor/usr vendor/mediainfo

      - name: Compressing Output
        continue-on-error: true
        run: |
          tar -zcvf mediainfo_20.09.tar.gz vendor
          curl --upload-file ./mediainfo_20.09.tar.gz https://transfer.sh/mediainfo_20.09.tar.gz
          echo "    Done."
